parser: "@typescript-eslint/parser"
extends: ["plugin:@typescript-eslint/recommended"]
plugins: ["@typescript-eslint"]
env:
    node: true
    es2021: true
parserOptions:
    ecmaVersion: latest
    sourceType: module
ignorePatterns: ["**/*", "!./src/**/*"]
rules:
    linebreak-style: [0, unix]
    semi: [2, always]
    omitLastInOneLineBlock: true
    no-mixed-spaces-and-tabs: [2, false]
    no-trailing-spaces: 1
    eqeqeq: warn
    strict: 2